### ISSUE TITLE
problem dji googles v2  015

### ISSUE THREAD

**Issue by ellsiprod** [fpv-wtf/margerine#16] opened 2022-04-20 15:42 UTC
hi i have this problem. my dji googles v2 are back from dji and they have the new firmware 015. my dji fpv holds dronehack 00 what can i do?

**Comment by a1axx** [comment] 2022-04-20 16:47
This was raised in issue #1

**Comment by ellsiprod** [comment] 2022-04-20 18:22
where can i see the solution?

**Comment by NiklasVoigt** [comment] 2022-04-20 21:04
there is no solution

**Comment by j005u** [comment] 2022-04-21 11:25
Closing as dupe of #1.

**Closed by j005u** 2022-04-21 11:25 UTC
